apiVersion: versionlens.com/v1
kind: Version

# k8s metadata
metadata:
  name: demo-todo--main--copper-alien

# need to have metadata
customerCompany: "demo-todo"
project: "main"
versionName: "copper-alien"

# nice to have metadata
triggeredBySourceRepository: "git@github.com:VersionLens/version-lens-version-repository.git"
triggeredBySourceRepositoryBranch: "origin/project/main"
triggeredBySourceRepositoryCommit: "0f7946a7ebd2445c882ad6c23fb66c36c97b1678"

# git clone
versionRepository: "https://github.com/VersionLens/demo-todo-version-repository.git"
versionRepositoryCommit: "5e7eb3acca23ba94a04d77a43312e90a95a2212c"

# argocd
destinationClusterName: "demo-todo"
