apiVersion: versionlens.com/v1
kind: Version

# k8s metadata
metadata:
  name: demo-todo--main--copper-alien

# need to have metadata
customerCompany: "demo-todo"
project: "main"
versionName: "copper-alien"

# git clone
versionRepository: "https://github.com/VersionLens/demo-todo-version-repository.git"
versionRepositoryCommit: "5e7eb3acca23ba94a04d77a43312e90a95a2212c"

# argocd
destinationClusterName: "demo-todo"

# parameters
params:
  demo-todo-frontend:
    DEMO_TODO_FRONTEND_SHA: ff58cc556269ede04ef6045465aafb2ed5747903
  demo-todo-backend:
    DEMO_TODO_BACKEND_SHA: 142b56b046d32eef4dc159359cb29d54a4c02b98
